# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 532b7ea93680e289c77023dfc1f122e46192db4aea32367c46760f7f4fca204c08b70747ab5ff8f299c7230bf5255a169201b95022a365ed8e7eed92e41581ba

test:
  secret_key_base: 1556ba89553f6ed026752d35ee9fc144ab982c0d8ba0753fb3542c688cd7d1c706ab239caecd04c7ed05ae6c2691cf62c31cc50940bc85fb80e32c0f0b5dfc29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
